use_frameworks!

target 'WTCarouselFlowLayout_Example' do
  pod 'WTCarouselFlowLayout', :path => '../'

  target 'WTCarouselFlowLayout_Tests' do
    inherit! :search_paths

    pod 'Quick', '1.2.0'
  pod 'Nimble', '7.0.2'
  end
end
