use_frameworks!

target 'WTCarouselFlowLayout_Example' do
  pod 'WTCarouselFlowLayout', :path => '../'

  target 'WTCarouselFlowLayout_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
